{{ cookiecutter.project_name }}_project/{{ cookiecutter.project_name }}/apps/core/urls.py
from django.conf import settings
from django.urls import re_path
from django.urls import path

from . import views

app_name = "core"
urlpatterns = [
    path('page/<slug:slug>', views.PageView.as_view(), name='page')
]


if settings.DEBUG:
    urlpatterns += [
        re_path(r'^(?!static).*(js|images|css|fonts).*$', views.StaticRedirectView.as_view(), name='static_redirect'),
        re_path(r'[a-z]*(/[a-z])*.html$', views.AnyHtmlView.as_view(), name='html_redirect')
    ]

{{ cookiecutter.project_name }}_project/{{ cookiecutter.project_name }}/apps/users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    # views
    path('signin/', views.SignInView.as_view(), name='signin'),
    path('password-change/', views.CustomPasswordChangeView.as_view(), name='passwordchange'),
    path('password-change-done/', views.CustomPasswordChangeDoneView.as_view(), name='passwordchangedone'),
]

{{ cookiecutter.project_name }}_project/{{ cookiecutter.project_name }}/config/urls.py
from django.conf.urls.static import static
from django.conf.urls import include
from django.contrib import admin
from django.conf import settings
from django.urls import path


urlpatterns = [
    path('users', include('apps.users.urls')),
    path('', include('apps.content.urls')),
    path('', include('apps.core.urls')),
    path('admin/', admin.site.urls),
]


handler400 = "apps.core.views.error_400_view"
handler403 = "apps.core.views.error_403_view"
handler404 = "apps.core.views.error_404_view"
handler500 = "apps.core.views.error_500_view"


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls)), ]

{{ cookiecutter.project_name }}_project/{{ cookiecutter.project_name }}/apps/core/models.py
from django.db import models


class Seo(models.Model):
    url = models.CharField(max_length=200, unique=True, blank=True, verbose_name='Url',
                           help_text='Activates on this url. If empty usually active.')
    title_tag = models.CharField(max_length=200, verbose_name='Title')
    meta_description = models.TextField(verbose_name='Description')

    objects = models.Manager()

    def __str__(self):
        if self.url:
            return '/{}: {}'.format(self.url, self.title_tag)
        return self.title_tag

    class Meta:
        verbose_name = 'Seo Setting'
        verbose_name_plural = 'Seo Settings'


class Code(models.Model):
    name = models.CharField(max_length=200, verbose_name='Name')
    url = models.CharField(max_length=200, blank=True, verbose_name='Url')
    LOCATIONS = [('HEAD', 'Head'), ('BODY', 'Body')]
    location = models.CharField(choices=LOCATIONS, max_length=200, verbose_name='Location',
                                help_text='Where is the code supposed to be?')
    code = models.TextField(verbose_name='Code', help_text='The code is not validated and should be correct.')

    objects = models.Manager()

    def __str__(self):
        if self.url:
            return '/{}: {}'.format(self.url, self.name)
        return self.name

    class Meta:
        verbose_name = 'Code'
        verbose_name_plural = 'Code'


class Page(models.Model):
    name = models.CharField(max_length=200, verbose_name='Name')
    slug = models.SlugField(unique=True, verbose_name='Slug',
                            help_text='How the page shows up in the url.')
    shown_in_footer_other = models.BooleanField(verbose_name='Shown in the footer section other',
                                                help_text='Should a link to the page in the footer be displayed?')
    shown_in_footer_legal = models.BooleanField(verbose_name='Shown in the footer section legal',
                                                help_text='Should a link to the page in the footer be displayed?')
    shown_in_navigation = models.BooleanField(verbose_name='Shown in the navigation',
                                              help_text='Should a link to the page in the navigation be displayed?')
    html_activated = models.BooleanField(verbose_name='Html Code Activated',
                                         help_text='Should the content be rendered as html?')
    content = models.TextField(verbose_name='Content')

    objects = models.Manager()

    class Meta:
        verbose_name = 'Page'
        verbose_name_plural = 'Pages'

    def __str__(self):
        return str(self.name)

{{ cookiecutter.project_name }}_project/{{ cookiecutter.project_name }}/apps/users/models.py
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    pass

{{ cookiecutter.project_name }}_project/{{ cookiecutter.project_name }}/apps/users/forms.py
from django import forms

{{ cookiecutter.project_name }}_project/{{ cookiecutter.project_name }}/apps/core/views.py
from django.views.generic.base import ContextMixin
from django.views.generic import RedirectView
from django.views.generic import TemplateView
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy

from .models import Page
from .models import Code
from .models import Seo

import re


class WebsiteContextMixin(ContextMixin):
    def get_seo_data(self):
        seos = []
        for seo in Seo.objects.all():
            if seo.url in self.request.get_full_path():
                seos.append(seo)

        if not seos:
            seo = Seo.objects.filter(url='').first()
            if seo:
                return {'title': seo.title_tag, 'description': seo.meta_description}
            else:
                return {'title': 'No title yet.', 'description': 'No description yet.'}

        final_seo = None
        slug_length = -1
        for seo in seos:
            seo_slug_length = len(seo.url)
            if seo_slug_length > slug_length:
                final_seo = seo
                slug_length = seo_slug_length

        return {'title': final_seo.title_tag, 'description': final_seo.meta_description}

    def get_custom_code(self):
        header_code = ''
        footer_code = ''
        custom_codes = []
        for custom_code in Code.objects.all():
            cc_slug = custom_code.url
            if cc_slug == '' or cc_slug in self.request.get_full_path():
                custom_codes.append(custom_code)
        for custom_code in custom_codes:
            if custom_code.location == 'HEAD':
                header_code += custom_code.code
            else:
                footer_code += custom_code.code
        return {'header_code': header_code, 'footer_code': footer_code}

    def get_static_pages(self):
        pages_footer_other = Page.objects.filter(shown_in_footer_other=True)
        pages_footer_legal = Page.objects.filter(shown_in_footer_legal=True)
        pages_navigation = Page.objects.filter(shown_in_navigation=True)
        pages = Page.objects.all()
        return {'pages_footer_other': pages_footer_other, 'pages_navigation': pages_navigation, 'pages': pages,
                'pages_footer_legal': pages_footer_legal}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(self.get_seo_data())
        context.update(self.get_custom_code())
        context.update(self.get_static_pages())
        return context


class PageView(WebsiteContextMixin, TemplateView):
    template_name = 'qc_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'slug' in kwargs:
            context['page'] = get_object_or_404(Page, slug=kwargs['slug'])
        return context


class StaticRedirectView(RedirectView):
    def get(self, request, *args, **kwargs):
        current_url = self.request.get_full_path()
        splitted_url = re.split(r'(js|images|css)', current_url)
        url = ''.join(splitted_url[1:])
        static_url = '/static/' + url
        return HttpResponseRedirect(static_url)


class AnyHtmlView(WebsiteContextMixin, TemplateView):
    def get(self, *args, **kwargs):
        current_url = self.request.get_full_path()
        current_url = current_url.strip('/')
        self.template_name = current_url
        return super().get(self, *args, **kwargs)


def error_400_view(request, exception=None):
    return HttpResponseRedirect(reverse_lazy('content:index'))


def error_403_view(request, exception=None):
    return HttpResponseRedirect(reverse_lazy('content:index'))


def error_404_view(request, exception=None):
    return HttpResponseRedirect(reverse_lazy('content:index'))


def error_500_view(request, exception=None):
    return HttpResponseRedirect(reverse_lazy('content:index'))

{{ cookiecutter.project_name }}_project/{{ cookiecutter.project_name }}/apps/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.views import generic
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.views import PasswordChangeDoneView
from django.urls import reverse_lazy


class CustomPasswordChangeView(PasswordChangeView):
    template_name = 'users/passwordchange.html'
    success_url = reverse_lazy('users:passwordchangedone')


class CustomPasswordChangeDoneView(PasswordChangeDoneView):
    template_name = 'users/passwordchangedone.html'


class SignInView(LoginView):
    template_name = 'users/signin.html'

{{ cookiecutter.project_name }}_project/{{ cookiecutter.project_name }}/apps/core/templates/users/passwordchange.html
{% raw %}
<!doctype html>

{% load static %}
{% load svg %}

<html lang="en">

<head>
	{% include 'partials/head.html' %}
</head>

<body>

	<section>
		<div class="d-flex flex-column justify-content-center min-vh-100">
			<div class="d-flex flex-column">
				<div class="row d-flex justify-content-center align-items-center">
					<div class="col-12 col-md-6 col-lg-4">
						<h1>Settings</h1>
						<hr class="hr">
						<h2>Change Password</h2>

						{% if form.non_field_errors %}
							<div class="alert alert-warning alert-dismissible fade show" role="alert">
								{% for error in form.non_field_errors %}
									{{ error }}
									<button type="button" class="close" data-dismiss="alert" aria-label="Close">
										<span aria-hidden="true">&times;</span>
									</button>
								{% endfor %}
							</div>
						{% endif %}

						<form method="POST">

							{% csrf_token %}

							{% for field in form %}
								<div class="form-group">
									
									<label>{{ field.label }}</label>
									{% if field.errors %}
										<input name="{{ field.html_name }}" type="{{ field.field.widget.input_type }}" class="form-control is-invalid" value="{{ field.value|default_if_none:'' }}">
										{% if field.help_text %}
											<small class="form-text text-muted">
												{{ field.help_text|safe }}
											</small>
										{% endif %}
										<div class="invalid-feedback">
											{{ field.errors }}
								      	</div>
								    {% else %}
								    	<input name="{{ field.html_name }}" type="{{ field.field.widget.input_type }}" class="form-control" value="{{ field.value|default_if_none:'' }}">
										{% if field.help_text %}
											<small class="form-text text-muted">
												{{ field.help_text|safe }}
											</small>
										{% endif %}
									{% endif %}
							        	
								</div>
							{% endfor %}

							<input class="btn btn-primary" type="submit" value="Change my password">
						</form>

						<hr>
						<a href="{% url 'content:main' %}">Back</a>
					</div>
				</div>
			</div>
		</div>
	</section>

	<!-- JAVASCRIPT -->
	<!-- ================================================== -->
	{% include 'partials/scripts.html' %}

</body>

</html>
{% endraw %}

{{ cookiecutter.project_name }}_project/{{ cookiecutter.project_name }}/apps/core/templates/users/passwordchangedone.html
{% raw %}
<!doctype html>

{% load static %}
{% load svg %}

<html lang="en">

<head>
	{% include 'partials/head.html' %}
</head>

<body>

	<section>
		<div class="d-flex flex-column justify-content-center min-vh-100">
			<div class="d-flex flex-column">
				<div class="row d-flex justify-content-center align-items-center">
					<div class="col-12 col-md-6 col-lg-4">
						<h1>Settings</h1>
						<hr class="hr">
						<h2>Password Change Done</h2>
						<p>Your password was changed</p>
						<hr>
						<a href="{% url 'content:main' %}">Back</a>
					</div>
				</div>
			</div>
		</div>
	</section>

	<!-- JAVASCRIPT -->
	<!-- ================================================== -->
	{% include 'partials/scripts.html' %}

</body>

</html>
{% endraw %}

{{ cookiecutter.project_name }}_project/{{ cookiecutter.project_name }}/apps/core/templates/users/signin.html
{% raw %}
{% load static %}
{% load svg %}


<!doctype html>
<html lang="en">
<head>
	{% include 'partials/head.html' %}
</head>
<body>


	<section>
		<div class="d-flex flex-column justify-content-center min-vh-100">
			<div class="row d-flex justify-content-center align-items-center">
				<div class="col-12 col-md-6 col-lg-4">
					<div class="mb-10">

						{% if form.errors %}
							<div class="alert alert-warning alert-dismissible fade show" role="alert">
								Your username and password didn't match. Please try again.
								<button type="button" class="close" data-dismiss="alert" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
							</div>
						{% endif %}

						{% if next %}
							{% if user.is_authenticated %}
								<div class="alert alert-warning alert-dismissible fade show" role="alert">
									Your account doesn't have access to this page. To proceed, please login with an account that has access.
									<button type="button" class="close" data-dismiss="alert" aria-label="Close">
										<span aria-hidden="true">&times;</span>
									</button>
								</div>
							{% else %}
								<div class="alert alert-success alert-dismissible fade show" role="alert">
									Please login to see this page.
									<button type="button" class="close" data-dismiss="alert" aria-label="Close">
										<span aria-hidden="true">&times;</span>
									</button>
								</div>
							{% endif %}
						{% endif %}

						<form method="post" action="{% url 'users:signin' %}">
							{% csrf_token %}
							<div class="form-group">
								<label for="exampleInputEmail1">{{ form.username.label }}</label>
								<input name="username" type="text" class="form-control" aria-describedby="emailHelp" value="{{ form.username.value|default_if_none:'' }}" placeholder="Username">
								<small class="form-text text-muted">For example: m.mustermann.</small>
							</div>
							<div class="form-group">
								<label for="exampleInputPassword1">{{ form.password.label }}</label>
								<input name="password" type="password" class="form-control" value="" placeholder="Password">
							</div>
							<button type="submit" class="btn btn-primary">Login</button>
							<input type="hidden" name="next" value="{{ next }}">
						</form>
					</div>

				</div>
			</div>
		</div>
	</section>


	<!-- JAVASCRIPT -->
	<!-- ================================================== -->
	{% include 'partials/scripts.html' %}

</body>
</html>
{% endraw %}